server {
    listen 80;
    listen [::]:80;

    server_name localhost; # Замени на свой домен или оставь localhost для dev

    root /var/www/public; # Путь к папке public твоего Laravel проекта

    index index.php index.html;

    charset utf-8;

    client_max_body_size 200M;

    # Безопасность
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    # Основной роут — Laravel
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Фавикон и robots.txt без логов
    location = /favicon.ico { access_log off; log_not_found off; }
    location = /robots.txt  { access_log off; log_not_found off; }

    # Ошибка 404 — перенаправляем на Laravel
    error_page 404 /index.php;

    # PHP-FPM обработка
    location ~ ^/index\.php(/|$) {
        fastcgi_pass app:9000; # Имя контейнера PHP-FPM или сокет
        fastcgi_index index.php;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param QUERY_STRING $query_string;

        fastcgi_hide_header X-Powered-By;
    }

    # Блокировка скрытых файлов и папок (.env, .git, .htaccess и т.п.)
    location ~ /\.(?!well-known).* {
        deny all;
    }

    # Optional: кэширование статики (js/css/img)
    location ~* \.(?:jpg|jpeg|gif|png|ico|css|js|woff2?|eot|ttf|svg)$ {
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }
}
